server:
  host: "0.0.0.0"
  port: "8080"
  env: "development"

database:
  url: "postgres://postgres:password@db:5432/bluehorntech?sslmode=disable"
  maxOpenConnection: 25
  maxIdleConnection: 10

service:
  maxDistanceError: 10000.0       # 10 km - very permissive for development
  maxDistanceWarning: 5000.0      # 5 km - warning threshold
  maxEarlyClockInSeconds: 900
  maxLateClockInSeconds: 1800 
  minVisitDurationSeconds: 1800
