services:
  db:
    image: postgres:15-alpine
    container_name: evv_db
    environment:
      POSTGRES_DB: bluehorntech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - evv_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bluehorntech"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: dev.Dockerfile
    container_name: evv_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - evv_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  evv_network:
    driver: bridge
